import type { Metadata } from "next";
import { Finlandica } from "next/font/google";
import "./globals.css";

const finlandica = Finlandica({
  subsets: ['latin'],
  variable: "--font-finlandica",
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${finlandica.variable} font-finlandica antialiased`}>
        {children}
      </body>
    </html>
  );
}